### ISSUE TITLE
General todo

### ISSUE THREAD

**Issue by famfo** [famfo/frog_bsd#2]
- [ ] Get scheduler to work (#1)
- [ ] Get elf execution to work
- [ ] Get syscalls to work
- [ ] Rewrite the allocator
- [ ] Write a libc
- [ ] Write drivers (storage, graphics, file systems)
